# Generated by Django 4.1.1 on 2022-11-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_userprofile_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='cvv',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='nrotarjeta',
            field=models.PositiveIntegerField(),
        ),
    ]
